[workspace]
members = [
    "crates/phonon-asr",
    "crates/phonon-audio",
    "crates/phonon-cli",
    "crates/phonon-core",
    "crates/phonon-llm",
    "crates/phonon-profile",
]
resolver = "2"

[workspace.package]
version = "0.1.7"
edition = "2021"
publish = false

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
which = "7"
